### ISSUE TITLE
[FLAUTO]  Progress bar on lock-screen

### ISSUE THREAD

**Issue by Larpoux** [dooboolab/flutter_sound#236]
### Version of flutter_sound
FLAUTO

### Platforms you faced the error (IOS or Android or both?)
ios

### Expected behavior
The progress bar should progress on the lock-screen

### Actual behavior
Sometimes the progress bar does not progress.
Some other times it is erroneous

### Tested environment (Emulator? Real Device?)
Real iphone 5s

### Steps to reproduce the behavior
With the example provided by  @salvatore373 : 
- start a fresh startup of the example
- does not change anything (Media: is "Remote Example File")
- press the "Play" button
- switch the iphone Off and On to have the lock-screen
- ... The progress bar does not progress...

Note: I had to patch the instruction : 
```C
isPlaying = false; 
```
In procedure ```audioPlayerDidFinishPlaying``` to be able to replay the song.
But not better for the following playbacks.

**Comment by salvatore373** [comment]
I can't test the example app on iOS at the moment, but I believe that the progress bar in the lock-screen is never updated, even without switching the iPhone OFF and ON.
Maybe we could solve this issue by calling `setupNowPlaying()` (in native iOS code) in `updateProgress()` whenever we get an update about the progress of the track.
I will check it this evening and keep you updated.

**Comment by salvatore373** [comment]
I followed the instructions that I put in my previous comment and I think that I fixed this issue in my [last commit](https://github.com/salvatore373/flutter_sound/tree/95380c82a777845a086d58741d0654b4cfb22cbf). Please check the code and let me know if you agree with the changes and if the error still occurs.

**Comment by Larpoux** [comment]
Hi @salvatore373 ,

I tested your example and it is OK.
I cannot test on my own apps, because I do not use ```Remote Album Arts``` on the lock-screen, but an Icon resource.

On my branch, the object "Track" has two members : 
- albumArtUrl
- albumArtAsset

The caller can fill one of those two files if he/she wants to have an image on its lock-screen.

**Comment by Larpoux** [comment]
The problem still occurs in #243 .
Maybe we need to merge @salvatore373 commit into this branch.

**Comment by Larpoux** [comment]
I will reopen this issue later, now that 3.1.1 is released
