### ISSUE TITLE
Runtime Exception in the production

### ISSUE THREAD

**Issue by kmusham** [dooboolab/flutter_sound#272]
There are thousands of runtime exception thrown recently wit the libraries in the production. following stack trace is from the google playstore. Mostly happenning on Android 9 and 10
Could you please quickly look at this? 

### Version of flutter_sound
3.0.0
### Platforms you faced the error (IOS or Android or both?)
android (I did not check iOs yet)
### Actual behavior
java.lang.RuntimeException: 
  at android.app.ActivityThread.handleCreateService (ActivityThread.java:3632)
  at android.app.ActivityThread.access$1400 (ActivityThread.java:210)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1751)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:193)
  at android.app.ActivityThread.main (ActivityThread.java:6776)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:911)
Caused by: java.lang.NullPointerException: 
  at com.dooboolab.fluttersound.BackgroundAudioService.b (Unknown Source:66)
  at com.dooboolab.fluttersound.BackgroundAudioService.onCreate (Unknown Source:6)
  at android.app.ActivityThread.handleCreateService (ActivityThread.java:3620)

**Comment by Larpoux** [comment]
Please use the last released version (3.1.5).
Some bugs are fixed for Android, since 3.0.0

**Comment by kmusham** [comment]
Is it a known issue in 3.0.0? App must be crashing with the runtime errors. 
I do not want to make the code changes based on new APIs because I see tons of changes needed to use new APIs also need lot of testing. Instead, I would like to update the API version to 3.5.1 but still use same old code ex: use FlutterSound class etc ..

Do you think that helps would solve the runtime exceptions ?

**Comment by Larpoux** [comment]
Yes, this bug has been found and fixed since 3.0.0.

You probably can use the last version of flutter_sound with your actual code : 
We tried to ensure backward compatibility with version 2.x.x (and 3.0.0 of course)

**Comment by Larpoux** [comment]
This bug was fixed in version 3.0.0+1
```
## 3.0.0+1

- bugfix [#254](https://github.com/dooboolab/flutter_sound/issues/254)
```

This is the only change since 3.0.0

**Comment by kmusham** [comment]
Thanks.
Seem like I can not simply create the iOS build without changes. I started making changes to Podfile and upgrade the target version to 9.3 but I still see the following issues.

ex: 
$ pod install
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "flutter_ffmpeg/<package name>":
  In Podfile:
    flutter_ffmpeg/<package name> (from `.symlinks/plugins/flutter_ffmpeg/ios`)

None of your spec sources contain a spec satisfying the dependency: `flutter_ffmpeg/<package name> (from `.symlinks/plugins/flutter_ffmpeg/ios`)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
$:

**Comment by Larpoux** [comment]
You could look to the README, section ```FFmpeg```.
This probably fix your dependency problem.

(But using an old iOS SDK is discouraged by Apple. You will not be allowed to upload your App to the Apple App Store.

**Comment by kmusham** [comment]
I resolved iOS build issue. 
So, can you please conform if the above Runtime Exceptions will be gone with the latest library version 3.5.1+ but the old code?

**Comment by Larpoux** [comment]
Yes, I do.

**Comment by Larpoux** [comment]
Feel free to re-open this issue if you think that your issue is not correctly handled.
