### ISSUE TITLE
Crash when adjusting volume while playing on Android device

### ISSUE THREAD

**Issue by howiesommerfeld** [dooboolab/flutter_sound#300]
### Version of flutter_sound
3.1.6

## flutter doctor
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E287, locale en-US)
 
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc2)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.44.1)
[!] Connected device
    ! No devices available

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
Volume should increase/decrease depending on if volume up/down was pushed

### Actual behavior
App crashes

### Tested environment (Emulator? Real Device?)
Real device, details attached below
<img width="1249" alt="Screen Shot 2020-04-17 at 10 18 59 AM" src="https://user-images.githubusercontent.com/1191945/79547922-f1e42f80-8094-11ea-8a04-bfa03a7eda39.png">

### Steps to reproduce the behavior
Play a file from a url using the Trackplayer. While track is playing, adjust volume.

Stacktrace:

Fatal Exception: java.lang.RuntimeException: Unable to create service com.dooboolab.fluttersound.BackgroundAudioService: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:2801)
       at android.app.ActivityThread.access$1800(ActivityThread.java:155)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1400)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5343)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)

**Comment by Larpoux** [comment]
Please, try the last version of flutter_sound : 3.1.10.

We are currently working on this bug it it is possibly fixed in 3.1.10.
Please check and tell us if OK.

**Comment by howiesommerfeld** [comment]
Just upgraded to 3.1.10 and the bug is still present. This time (using same test device as above), it crashed before changing volume, on its own after 2 or 3 seconds of playback.

**Comment by Larpoux** [comment]
We need your new logs (after upgrading to 3.1.10)

**Comment by howiesommerfeld** [comment]
> We need your new logs (after upgrading to 3.1.10)

Fatal Exception: java.lang.RuntimeException: Unable to create service com.dooboolab.fluttersound.BackgroundAudioService: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:2801)
       at android.app.ActivityThread.access$1800(ActivityThread.java:155)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1400)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5343)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)

Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
       at com.dooboolab.fluttersound.BackgroundAudioService.b()
       at com.dooboolab.fluttersound.BackgroundAudioService.onCreate()
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:2791)
       at android.app.ActivityThread.access$1800(ActivityThread.java:155)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1400)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5343)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)

**Comment by Larpoux** [comment]
Are you really sure to use 3.1.10 ?
Did you do a `flutter pub get` ?
can you post the result of `flutter pub deps` ?

**Comment by howiesommerfeld** [comment]
> Are you really sure to use 3.1.10 ?
> Did you do a `flutter pub get` ?
> can you post the result of `flutter pub deps` ?

Sure, see results below:

flutter pub deps
Dart SDK 2.7.2
Flutter SDK 1.12.13+hotfix.9
bite_casts 1.0.1+1
|-- cloud_firestore 0.13.4
|   |-- cloud_firestore_platform_interface 1.1.0
|   |   |-- collection...
|   |   |-- firebase_core...
|   |   |-- flutter...
|   |   |-- meta...
|   |   '-- plugin_platform_interface 1.0.2
|   |       '-- meta...
|   |-- cloud_firestore_web 0.1.1
|   |   |-- cloud_firestore_platform_interface...
|   |   |-- firebase 7.2.1
|   |   |   |-- http 0.12.0+4
|   |   |   |   |-- async...
|   |   |   |   |-- http_parser...
|   |   |   |   |-- path...
|   |   |   |   '-- pedantic...
|   |   |   |-- http_parser...
|   |   |   '-- js...
|   |   |-- firebase_core...
|   |   |-- flutter...
|   |   |-- flutter_web_plugins 0.0.0
|   |   |   |-- collection...
|   |   |   |-- flutter...
|   |   |   |-- meta...
|   |   |   |-- typed_data...
|   |   |   '-- vector_math...
|   |   |-- http_parser 3.1.3
|   |   |   |-- charcode...
|   |   |   |-- collection...
|   |   |   |-- source_span...
|   |   |   |-- string_scanner...
|   |   |   '-- typed_data...
|   |   |-- js 0.6.1+1
|   |   '-- meta...
|   |-- firebase_core...
|   |-- flutter...
|   '-- meta...
|-- cupertino_icons 0.1.3
|-- firebase_admob 0.9.3+1
|   |-- firebase_core...
|   |-- flutter...
|   |-- meta...
|   '-- platform 2.2.1
|-- firebase_analytics 5.0.11
|   |-- flutter...
|   '-- meta...
|-- firebase_auth 0.15.0
|   |-- firebase_core...
|   |-- flutter...
|   '-- meta...
|-- firebase_core 0.4.4
|   |-- firebase_core_platform_interface 1.0.4
|   |   |-- flutter...
|   |   |-- meta...
|   |   |-- plugin_platform_interface...
|   |   '-- quiver...
|   |-- firebase_core_web 0.1.1+2
|   |   |-- firebase...
|   |   |-- firebase_core_platform_interface...
|   |   |-- flutter...
|   |   |-- flutter_web_plugins...
|   |   |-- js...
|   |   '-- meta...
|   |-- flutter...
|   '-- meta...
|-- firebase_crashlytics 0.1.3+3
|   |-- flutter...
|   '-- stack_trace 1.9.3
|       '-- path...
|-- firebase_dynamic_links 0.5.0+11
|   '-- flutter...
|-- firebase_storage 3.1.3
|   |-- firebase_core...
|   '-- flutter...
|-- flutter 0.0.0
|   |-- collection 1.14.11
|   |-- meta 1.1.8
|   |-- sky_engine 0.0.99
|   |-- typed_data 1.1.6
|   '-- vector_math 2.0.8
|-- flutter_platform_widgets 0.32.4
|   '-- flutter...
|-- flutter_sound 3.1.10
|   |-- flutter...
|   |-- flutter_ffmpeg 0.2.10
|   |   '-- flutter...
|   |-- path...
|   |-- path_provider...
|   '-- permission_handler 5.0.0+hotfix.3
|       |-- flutter...
|       |-- meta...
|       '-- permission_handler_platform_interface 2.0.0
|           |-- flutter...
|           |-- meta...
|           '-- plugin_platform_interface...
|-- flutter_test 0.0.0
|   |-- archive 2.0.11
|   |   |-- args...
|   |   |-- crypto...
|   |   '-- path...
|   |-- args 1.5.2
|   |-- async 2.4.0
|   |   '-- collection...
|   |-- boolean_selector 1.0.5
|   |   |-- source_span...
|   |   '-- string_scanner...
|   |-- charcode 1.1.2
|   |-- collection...
|   |-- convert...
|   |-- crypto...
|   |-- flutter...
|   |-- image 2.1.4
|   |   |-- archive...
|   |   '-- xml...
|   |-- matcher 0.12.6
|   |   '-- stack_trace...
|   |-- meta...
|   |-- path...
|   |-- pedantic 1.8.0+1
|   |-- petitparser 2.4.0
|   |   '-- meta...
|   |-- quiver 2.0.5
|   |   |-- matcher...
|   |   '-- meta...
|   |-- source_span 1.5.5
|   |   |-- charcode...
|   |   |-- path...
|   |   '-- term_glyph...
|   |-- stack_trace...
|   |-- stream_channel 2.0.0
|   |   '-- async...
|   |-- string_scanner 1.0.5
|   |   |-- charcode...
|   |   |-- meta...
|   |   '-- source_span...
|   |-- term_glyph 1.1.0
|   |-- test_api 0.2.11
|   |   |-- async...
|   |   |-- boolean_selector...
|   |   |-- collection...
|   |   |-- matcher...
|   |   |-- meta...
|   |   |-- path...
|   |   |-- pedantic...
|   |   |-- source_span...
|   |   |-- stack_trace...
|   |   |-- stream_channel...
|   |   |-- string_scanner...
|   |   '-- term_glyph...
|   |-- typed_data...
|   |-- vector_math...
|   '-- xml 3.5.0
|       |-- collection...
|       |-- convert...
|       '-- petitparser...
|-- image_picker 0.6.4
|   |-- flutter...
|   '-- flutter_plugin_android_lifecycle 1.0.6
|       '-- flutter...
|-- intl 0.16.1
|   '-- path...
|-- path 1.6.4
|-- path_provider 1.6.5
|   |-- flutter...
|   |-- path_provider_macos 0.0.4
|   |   '-- flutter...
|   '-- path_provider_platform_interface 1.0.1
|       |-- flutter...
|       |-- meta...
|       |-- platform...
|       '-- plugin_platform_interface...
|-- provider 4.0.4
|   |-- collection...
|   |-- flutter...
|   '-- nested 0.0.4
|       '-- flutter...
|-- share 0.6.3+6
|   |-- flutter...
|   '-- meta...
'-- uuid 2.0.4
    |-- convert 2.1.1
    |   |-- charcode...
    |   '-- typed_data...
    '-- crypto 2.1.3
        |-- collection...
        |-- convert...
        '-- typed_data...

I did a clean and rebuild which seemed to be a bit better, but now getting another fatal error:

Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 24024012 byte allocation with 7324890 free bytes and 6MB until OOM
       at dalvik.system.VMRuntime.newNonMovableArray(VMRuntime.java)
       at android.graphics.Bitmap.nativeCreateFromParcel(Bitmap.java)
       at android.graphics.Bitmap.access$100(Bitmap.java:32)
       at android.graphics.Bitmap$1.createFromParcel(Bitmap.java:1498)
       at android.graphics.Bitmap$1.createFromParcel(Bitmap.java:1490)
       at android.os.Parcel.readParcelable(Parcel.java:2252)
       at android.os.Parcel.readValue(Parcel.java:2152)
       at android.os.Parcel.readArrayMapInternal(Parcel.java:2485)
       at android.os.BaseBundle.unparcel(BaseBundle.java:221)
       at android.os.BaseBundle.keySet(BaseBundle.java:321)
       at android.media.MediaMetadata$Builder.<init>(MediaMetadata.java:579)
       at android.media.session.MediaSession.setMetadata(MediaSession.java:416)
       at android.support.v4.media.session.d.a()
       at android.support.v4.media.session.MediaSessionCompat$g.a()
       at android.support.v4.media.session.MediaSessionCompat.a()
       at com.dooboolab.fluttersound.BackgroundAudioService.a()
       at com.dooboolab.fluttersound.BackgroundAudioService.a()
       at com.dooboolab.fluttersound.BackgroundAudioService$c.a()
       at com.dooboolab.fluttersound.BackgroundAudioService$c.onPostExecute()
       at android.os.AsyncTask.finish(AsyncTask.java:636)
       at android.os.AsyncTask.access$500(AsyncTask.java:177)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5343)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)

**Comment by Larpoux** [comment]
It seems that the Album Art that you passed as argument to ```startTrackPlayer()``` is incorrect, and does not point to a small image.

**Comment by howiesommerfeld** [comment]
Thanks for the feedback and immediate responsiveness when dealing with this issue. I've made use of a smaller file for the album art and am no longer receiving the crash.

**Comment by Larpoux** [comment]
You are welcome.
Do not hesitate to come back if you have others issues.
